### ISSUE TITLE
new dataset for episode-1

### ISSUE THREAD

**Issue by annefou** [NordicESMhub/deep_python#1]
I suggest to use another dataset for instance https://openei.org/doe-opendata/dataset/kimberly-well-borehole-geophysics-database for the first episode.

**Comment by annefou** [comment]
@yellowchocobo do you think this dataset is relevant for CEED?

**Comment by annefou** [comment]
And then which dataset would we use for episode 4 (multiple files).

**Comment by yellowchocobo** [comment]
Sorry, I didn't see that something was happening on GitHub :p. Sounds good with the new datasets. I will try to adapt the template around the new dataset. I think I will work with that tomorrow.

**Comment by annefou** [comment]
I have used the temperature anomalies (are in data folder) dataset for 01-numpy.md, etc. stopped at 05-cond.md (did not have time yet to look at it furter.

**Comment by yellowchocobo** [comment]
I guess using temperature anomalies is good for lessons 01-04, and we can maybe either use one of the datasets we got from one of the people attending for "Making Choices", "Creating Functions" and "Command-Line programs". I think the dataset from Eirik is rather easy to work with (a sediment core and how water content and ++ change with depth).

**Comment by annefou** [comment]
It sounds like a very good idea. Maybe worth checking with Eirik about the license. Is it OK to distribute such data?

**Comment by annefou** [comment]
Close this issue. Re-open if necessary.
