### ISSUE TITLE
Plan for the day (lessons soon to be submitted)

### ISSUE THREAD

**Issue by yellowchocobo** [NordicESMhub/deep_python#10]
I was thinking about making lessons about:

- Integrated Development Environments (IDEs) (showing quickly Spyder, Jupyter Notebook, Jupyter Lab and what are the advantages of using such IDEs)
- plotting (subplots, color bars and more options that can be useful, differences between imshow, pcolor and pcorlormesh, maybe 3D plotting but that's a bit more advanced?)
- a quick and short lesson on how to read tabular data (with open with, numpy loadtxt, numpy genfromtxt, and pandas option that will complement the already existing lessons)
- intro in numpy (which, will build upon on what is used in the already existing lessons, maybe could have a look at the top 10 or top 20 commands used in numpy)
- intro in pandas (as you suggested) with focus on both pandas array and time series

I will save the lessons into markdown and try to modify those files to the format of the carpentry template workshop. I might ask you some help with that.

**Comment by annefou** [comment]
- Integrated Development Environments (IDEs) (showing quickly Spyder, Jupyter Notebook, Jupyter Lab and what are the advantages of using such IDEs)

**use setup.md: it contains already how to start a jupyter notebook but nothing on Spyder and jupyterlab). to be noted that spyder is meant to be used for debugging python codes (we could show some examples; but probably not as part of the first 2 days).** 


- plotting (subplots, color bars and more options that can be useful, differences between imshow, pcolor and pcorlormesh, maybe 3D plotting but that's a bit more advanced?)

**use 07-visluzation.md: the current drafted list of items needs to be updated too...**

- a quick and short lesson on how to read tabular data (with open with, numpy loadtxt, numpy genfromtxt, and pandas option that will complement the already existing lessons)

**01-numpy.md and 06-pandas.md**

- intro in numpy (which, will build upon on what is used in the already existing lessons, maybe could have a look at the top 10 or top 20 commands used in numpy)

**One important thing to highlight is that numpy is used in most other packages dealing with arrays i.e. pandas, xarrays, scipy, etc. So learning numpy is very important**
 
- intro in pandas (as you suggested) with focus on both pandas array and time series

**06-pandas.md**

**Comment by annefou** [comment]
For the first 2 days, I guess we can have:

1. Analyzing Tabular Data 
2. Repeating Actions with Loops 
3. Storing Multiple Values in Lists 
4. Analyzing Data from Multiple Files 
5. Making Choices 
6. Working with Pandas dataframes 
7. Working with xarray 
8. Making plots with python 
9. Creating Functions 
10. Errors and Exceptions 
11. Command-Line Programs 
12. Defensive Programming 
13. Debugging 

What do you think @yellowchocobo ?

**Comment by yellowchocobo** [comment]
That sounds nice! I did not work with xarray yet but I guess it should not be too difficult to get familiar with this module? I am going to work both Saturday and Sunday (not the whole day but a little bit on both days. Hope to get things ready by Monday 💃 .

Btw, if I want to push a change what is the best? Fork the project, create a dev-branch, make changes, and make a push request? I am still trying to get use to GitHub :)

**Comment by annefou** [comment]
Yes, the easiest is to fork the repo, create a branch and make a pull request to nordicesmhub repo. Don't forget to sync your repo with mine before your pull request.

Let me know if you have problems.

**Comment by yellowchocobo** [comment]
Thanks

**Comment by yellowchocobo** [comment]
I will finish the lessons tomorrow. I got pretty far with all of them but still some work

**Comment by yellowchocobo** [comment]
I just have a copy locally for now
