### ISSUE TITLE
introduction of pandas

### ISSUE THREAD

**Issue by annefou** [NordicESMhub/deep_python#2]
In episode 1, we introduce numpy. It would be useful to have a section/episode on pandas after episode 1:
- the goal would be to show that most scientific python packages build on numpy

**Comment by annefou** [comment]
To be added after "making choices" i.e. before functions.

**Comment by yellowchocobo** [comment]
Good idea! I will try to make an "intro in pandas" chapter with both the basic command to handle an array in pandas and how to work with time series.

**Comment by annefou** [comment]
I'll write a template in _episodes/06-pandas.md

**Comment by annefou** [comment]
Just added it.

**Comment by yellowchocobo** [comment]
Nice :)
